version: '3.8'
volumes:
    node_modules_volume:

services:
    app:
        container_name: money_tool
        build: .
        ports:
            - 8080:8080
        privileged: true
        volumes:
            - .:/app/vue
            - node_modules_volume:/app/vue/node_modules
        tty: true
        stdin_open: true
        command: ['/bin/bash']